### ISSUE TITLE
Requesting your master's thesis

### ISSUE THREAD

**Issue by yanyuwei123** [reinharty/Branch-And-Price-for-the-Joint-Order-Batching-And-Picker-Routing-Problem#1]
It is a great honor to see the information you shared on GitHub, and I would like to express my sincere gratitude. May I ask if you can send me a copy of your master's thesis? Or where can I find your master's thesis. I searched through the abstract you provided earlier, but couldn't find it.

**Comment by yanyuwei123** [comment]
my Email is ：[deleted to avoid spam]

**Comment by reinharty** [comment]
Hi, 
yes, indeed, the thesis itself is not online, the abstract does only serve as a summary for context to the code.
I will see if I can find it.
Out of curiousity, how come that you are interested in this highly specific yet uncommon topic?

**Comment by yanyuwei123** [comment]
Thank you very much for your reply. Currently, I am a student. Due to the branch pricing method being a very practical approach in our field of operations research, I would like to conduct my own research. But I just started school and don't really understand anything. Therefore, some materials are needed for introductory learning.



> Hi, yes, indeed, the thesis itself is not online, the abstract does only serve as a summary for context to the code. I will see if I can find it. Out of curiousity, how come that you are interested in this highly specific yet uncommon topic?

**Comment by yanyuwei123** [comment]
> Thank you very much for your reply. Currently, I am a student. Due to the branch pricing method being a very practical approach in our field of operations research, I would like to conduct my own research. But I just started school and don't really understand anything. Therefore, some materials are needed for introductory learning.
> 
> > Hi, yes, indeed, the thesis itself is not online, the abstract does only serve as a summary for context to the code. I will see if I can find it. Out of curiousity, how come that you are interested in this highly specific yet uncommon topic?

If you can find it, I would greatly appreciate it

**Comment by reinharty** [comment]
Hi, I just send you the PDF and removed your mail, to avoid spamers finding it.

**Comment by yanyuwei123** [comment]
> Hi, I just send you the PDF and removed your mail, to avoid spamers finding it.

Yes, I have received the file you sent. Thank you very much.
